- pages/index.vue
- https://github.com/code4nagoya/covid19/issues/10
- 陽性患者数・陽性患者の属性のグラフは出せそうとのことなので、公開にむけて最小限のグラフにする
> 愛知県にないデータのグラフを一時的に非表示

- README.md
ステータスバッジURLが東京のリポジトリのままだったので、愛知のリポジトリのURLに変更
> ステータスバッジのURLを愛知のものに変更

- nuxt.config.ts
- pages/index.vue
issue : https://github.com/code4nagoya/covid19/issues/12
- タイトルの都内->愛知県内
- OGPの画像とリンク系のURLを変更
> タイトルとOGPを愛知県のものに変更

- components/SideNavigation.vue
- close #69 
- スマホ版でもスクロールできることを確認しました
- 以下で動作することを確認しました。
- Chrome 80.0.3987.132
- Firefox 73.0.1
- Safari 13.0.5
> スマホ版でサイドバーがスクロールできないバグを解消

- pages/government.vue
- close #74 
- 埼玉県版を追加しました。
- 都道府県の順番は本家に則り以下記載の順番としました
https://www.mhlw.go.jp/topics/2007/07/dl/tp0727-1d.pdf
> 埼玉県版をリンク追加

- components/TimeBarChart.vue
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. の修正
see; https://stackoverflow.com/questions/54334676/chart-js-format-date-in-label
> Fix Deprecation warning in chart.js

- components/DesktopFlowSvg.vue
- pages/flow.vue
- close #104 
3/19 付けの情報で、
https://www.pref.aichi.jp/site/covid19-aichi/soudan-korona.html
愛知県精神保健福祉センター
電話番号　052－962－5377
という相談窓口が増えたので「新型コロナウイルス感染症が心配なときに」に追加。
> 「新型コロナウイルス感染症が心配なときに」に愛知県精神保健福祉センターの窓口を追加する

- components/SideNavigation.vue
#108
- close #108
`components/SideNavigation.vue`
の県内の最新感染動向に該当する部分に
divider: trueを追記
> 「県内の最新感染動向」の下に罫線追加

- components/SideNavigation.vue
- pages/index.vue
- pages/parent.vue
#112
- close #112
- 愛知県内の発生状況についてのリンクの修正
- 変更前: https://www.pref.aichi.jp/soshiki/kenkotaisaku/novel-coronavirus.html 
- 変更後: https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
- 新型コロナウイルス感染症にかかる相談窓口についてのリンクを修正
- 変更前: https://www.pref.aichi.jp/soshiki/kenkotaisaku/novel-coronavirus.html#soudan
- 変更後: https://www.pref.aichi.jp/site/covid19-aichi/soudan.html#soudan
> 愛知県内の発生状況と相談窓口へのリンク修正

- components/WhatsNew.vue
- pages/index.vue
#111
- close #111
「最新のお知らせ」の項目を北海道のサイトみたいに、愛知県の「[感染症対策ページ](https://www.pref.aichi.jp/site/covid19-aichi/)」へのリンクを貼る
リンク: https://www.pref.aichi.jp/site/covid19-aichi/
-  `components/WhatsNew.vue`
- timeのスタイルを調整しアイコンとリンクの間を開けるように変更
-  愛知県発表の新型コロナウイルス感染症に関する情報はこちらのテキスト
- リンク作成 https://www.pref.aichi.jp/site/covid19-aichi/
- `pages/index.vue`
- newsItemsから単数のnewsItemに変更
- newsItemに今回対応するurlとtextを入れて`components/WhatsNew.vue`に渡す
> 「最新のお知らせ」を愛知県のコロナに関するお知らせページへのリンクに変更

- components/DataTable.vue
- close #151
- 「検査陽性者の状況」から「※退院には、死亡退院を含む」の文言を削除
> 「検査陽性者の状況」から「※退院には、死亡退院を含む」の文言を削除

- components/DataView.vue
- components/SvgCard.vue
- pages/index.vue
#158 
- 出典元表記、出典元リンクを修正
-  「検査陽性者の状況」に出典元表記がないので追加
> 出典元表記、出典元リンクを追加+修正

- components/TimeBarChart.vue
- close #162 
- 「陽性患者数」、「検査実施件数」の「日別」の実績値の前にデータソースに記載された時点日時を表示します。「累計」の累計値の前に表示している値と同じものです。
いずれも修正対応後のものです。
> 実績値の前に、累計値と同様に、データソースに記載された時点日時を表示

- components/TimeBarChart.vue
- utils/formatGraph.ts
- utils/formatRemarks.ts
- close #209
* ``data.json`` で ``"合算": "〇"`` になっている日付のバー色を青に
* ``"合算": `` が ○以外 または 無し の場合は赤系
* Vue コンポーネントの都合上、検査実施件数 だけでなく 陽性患者数 にも対応しますがデータが無いので 陽性患者数 のチャートは変化無し
> 検査実施数グラフで集計単位の異なるデータを視覚的に区別した

- components/DateSelectSlider.vue
- components/TimeBarChart.vue
- components/TimeStackedBarChart.vue
- close #227 
- グラフに表示期間を指定できるスライダーを付けた
1. デフォルト期間は直近14日間
2. 最小期間は設けていない（北海道版とは実装が異なったためちょっと入れ辛くなった）
3. スライダーを動かすと表示期間に応じて縦軸も変動する
北海道版との相違点など、改善点あれば言ってください。
> 各グラフに表示期間を指定できるスライダーを追加

- components/SideNavigation.vue
- close #340 
- 左側メニューにリンクを追加
- リンク表記 : 「名古屋市新型コロナウイルス感染症対策特設サイト」
- リンク先 : https://nagoyabousai.maps.arcgis.com/apps/Cascade/index.html?appid=04c0250edfe54ae4af7f1c8755d275b5
- 愛知県関連のリンクとの間に罫線を追加
> 名古屋市のコロナ対策特設サイトへのリンク追加

- components/DataSelector.vue
- components/DataViewBasicInfoPanel.vue
- close #320
- 選択ボタンを小さくした
- 右上の数値を単位の間の謎の空白をなくした
> 画面幅が狭いと「週別 | 日別 | 累計」セレクトボタンがあるグラフの文字がはみ出す表示バグを修正

- components/ColumnMap.vue
- #350
- 画面幅切り替えの条件指定が間違っていたので修正
- 画面幅約 340px までなら収まるようになった
> 再:市町村別感染状況で画面幅がやや狭いと右にはみ出す

- nuxt.config.ts
- close #392 
- [Google Search Console](https://search.google.com/search-console?hl=ja) の所有者確認用のMetaタグを追加した。
> Google Search Consoleの所有者確認のMetaタグを追加

- pages/index.vue
- close #461
- 文言 5/14、政府は、愛知県の緊急事態宣言を解除しました。愛知県独自の「愛知県緊急事態宣言」は引き続き発出中です。
- リンク先 https://www.pref.aichi.jp/site/covid19-aichi/2020051402.html
に変更。
> 緊急事態宣言の解除（県独自は継続）に併せて、トップの文言を変更

- components/ColumnMap.vue
- pages/index.vue
- 市町村別感染者数の数字が累計であることを強調
- 感染者数→累計感染者数
- 市町村別感染状況→市町村別感染者数
- 凡例のレイアウト変更
> 「市町村別感染状況」が累計値であることを強調する #448

- components/MainSummaryChart.vue
- utils/types.ts
- close #779
- 検査陽性者状況の推移 の積み上げ棒グラフに[軽症・無症状]と[中等症]を追加
- 色は
- 中等症 #E6C79A
- 軽症無症状 #FEE4AA
- 注記に「7月24日より、[軽症中等症]が[軽症無症状]と[中等症]に分割されました」を追加
> [軽症・中等症]が[軽症・無症状]と[中等症]に分けられた事への対応（積み上げ棒グラフ側） 

- components/ColumnMap.vue
- components/TimeBarLineChart.vue
- utils/formatNumber.ts
- #524
- 以下に対して３桁カンマ区切りを適用
- グラフY軸
- ツールチップ
- 「判断指標と達成状況」の値
- 「市町村別感染状況」の感染者数（感染率は枠をはみ出すので対応せず）
※すべて対応完了したか不明なため、Issue は close せずに置いておきます。
> グラフのY軸ラベルや現在値に３桁カンマ区切りを適用する

- components/HospitalizedChart.vue
- utils/types.ts
- close #845
###「入院患者数グラフ」「判断指標と達成状況」
- 入院患者数には、main_summaryの「入院」に、値が有れば「入院」を使い、空なら「入院等」を用いる
- 移動平均は混在したまま算出する
- 注記に『7/27以前の「入院患者数」には、「入院調整」「自宅療養」「調整」が含まれています』と追記する
> 「入院患者数グラフ」と「判断指標と達成状況」の入院患者数を「入院等」から「入院」に変更

- components/NewPatientsChart.vue
Reverts code4nagoya/covid19#849
[復活した要請者一覧PDF(７月までと８月以降)に対応 #59](https://github.com/code4nagoya/covid19-aichi-tools/pull/59) に伴い、新規感染者数グラフの注記を元に戻した。
> Revert "新規感染者数グラフの注記の文言変更とCSVリンク削除"

- components/NewPatientsChart.vue
> fix 新規感染者数パネルの「当サイトでCSV形式に加工したデータ」のリンク先が正しくない 

- pages/index.vue
- #1138 
- 緊急事態宣言の終了予定日を 2/7 → 3/7 に変更
> 緊急事態宣言を3/7まで延長

- pages/index.vue
- close #1138
- Top ページの 緊急事態宣言 の欄を削除（また出るかも知れないのでコメントアウトしただけ）
> 緊急事態宣言が 2/28 をもって解除されたのでTop文言を削除

- components/SideNavigation.vue
> Fix: 名古屋防災マップ リンク切れ
