README.md

JA版README URLを愛知版に

---

README_EN.md
README_ES.md
README_KO.md
README_ZH_TW.md
layouts/default.vue
layouts/print.vue

replace tokyo url

---

components/SideNavigation.vue
pages/worker.vue

close #14 
- 「企業の皆様・はたらく皆様へ」を愛知県の情報に更新
- サイドバーの「東京都主催等 中止又は延期するイベント等」を愛知県の情報に更新

Convert worker info

---

components/SideNavigation.vue
pages/government.vue

- 北海道の自治体リンクに習って、追加してみました。
- 今後リンクが増えていくと、SNSボタンが隠れてしまいそうだったので、新しくpageを作ってみました 
-  /aboutのabout.vueをベースにcardviewをシンプルに使ってます

他の自治体サイトまとめページ追加

---

pages/about.vue

- close https://github.com/code4nagoya/covid19/issues/27
- データについての記載を削除 / remove about data section

Remove about data section

---

pages/government.vue

- close #36 
- 野良版閉鎖に伴い、公式版へリンク差し替え

神奈川県のリンク差し替え

---

components/DataView.vue
pages/index.vue

- close #41
- データ出典を愛知県ページに変更
- オープンデータではないので、文言も変更

Convert opendata link

---

README.md

READMEの翻訳版へのリンクを削除/ステージング環境の記載を削除

---

.github/CONTRIBUTING.md

- close #48
- tokyo を aichi に変更
- netlify の URL は間違っていたら後で直してください

CONTRIBUTING.md の tokyo を aichi に修正

---

pages/parent.vue

- close #47 
- 手洗いに関するリンクを差し替えました

手洗いに関するリンクの差し替え

---

components/SideNavigation.vue

知事からのメッセージのリンク先を差し替え

---

data/news.json

- close #31 
- 3/11時点での愛知県からのお知らせを追加しました
下記リンクからの情報を掲載しています
https://www.pref.aichi.jp/soshiki/list1-1.html

愛知県からのお知らせを最新に更新

---

nuxt.config.ts
pages/about.vue

お問い合わせ先をとりあえずCode for Nagoyaの代表アドレスに

---

.github/CONTRIBUTING.md

- close https://github.com/code4nagoya/covid19/issues/68
- CONTRIBUTING.mdの開発サイトを東京都のものから変更

Fix dev url

---

pages/worker.vue

- close #82 
- 「企業の皆様・はたらく皆様」のお知らせを追加

企業の皆様・はたらく皆様へのお知らせ追加

---

components/SideNavigation.vue

development -> master

---

components/SideNavigation.vue

- close #99 
- Twitter のリンクを変更しました。
- FacebookとLINEのアイコンを消しました。

FacebookとLineのアイコンをけして、Twitterのリンクを書き換えました

---

components/SideNavigation.vue

「他自治体の対策サイト」がリンク切れ #104

---

nuxt.config.ts

OGPの「愛知県が開設」という文言を「愛知県内外の有志が開設」に修正

---

pages/index.vue

- close #171
- 「検査実施数」グラフのタイトルを「検査実施件数」に変更

「検査実施数」グラフのタイトルを「検査実施件数」に変更

---

components/SideNavigation.vue

#176 
- サイドメニューにLINE、Twitteを追加
- 他自治体の対策サイトのリンク先を変更

サイドメニューの整理

---

pages/about.vue

#177 に対応しています．
協力，賛同団体の募集については触れられていません...
- 協力団体を追加

Add Cooperating-Organizations

---

pages/index.vue

- #146 
- 検査実施件数の注記を追記(3/22は3/16からの合算値)

検査実施件数の注記を修正

---

utils/formatGraph.ts

こちらへの対応
https://github.com/code4nagoya/covid19/issues/202

雑な型のデータでも累計の計算ができるように修正

---

pages/index.vue

Reverts code4nagoya/covid19#228
データが更新されたので検査結果の誤りについての注意書きを削除します。

Revert "検査結果の誤りについての注意書きを追加"

---

components/ConfirmedCasesTable.vue
pages/index.vue
utils/formatConfirmedCases.ts

- close #216
- 「検査陽性者の状況」に「施設入所」項目を追加

「検査陽性者の状況」に「施設入所」項目を追加

---

components/DataSelector.vue
components/TimeBarChart.vue
components/TimeStackedBarChart.vue
pages/index.vue
utils/formatGraph.ts
utils/formatInHospitalGraph.ts
utils/formatSevereGraph.ts

- close #243
- 陽性患者数と検査実施件数に週別表示を追加

陽性患者数と検査実施件数に週別表示を追加

---

pages/index.vue

- #461
愛知県HPが更新されたので、そのページへリンク先を変更、文言を少し修正
https://www.pref.aichi.jp/site/covid19-aichi/covid19-aichi.html

トップの文言とリンク先を小変更

---

.github/workflows/pr.yml

- close #1120
- Pull Request 送信先ブランチを development から master へ変更
- https://github.com/code4nagoya/covid19/issues/1120#issuecomment-761754342

Pull Request 送信先ブランチを development から master へ変更

---

components/NewPatientsChart.vue
utils/formatPatientsPerCities.ts

fix 3月データが無いときにエラーが出ていた
